"""core._cli_provider \u2014 `opencrayfish provider new` + `provider validate` helpers.

Split out from ``core/cli.py`` for the same reasons as
``_cli_tool.py`` / ``_cli_connector.py``: heavy triple-quoted
template strings live in dedicated files to keep the public CLI
short and avoid JSON-escape leaks in editor tools.

Provider backends are the LIGHTEST plug-in surface today \u2014 there is
no central ``BackendRegistry`` (the Provider singleton itself owns
the live primary/fallback backends). So ``provider validate`` is
the equivalent of ``connector validate`` but exercises
``resolve_backend_manifest`` directly rather than a registry.
"""
from __future__ import annotations

import argparse
import importlib
import re
import sys
from pathlib import Path
from textwrap import dedent

from core.provider_manifest import (
    SUPPORTED_BACKEND_PROTOCOL_VERSIONS,
    resolve_backend_manifest,
)

# Backend names commonly contain a hyphen-like separator (``hailo-ollama-npu``)
# but Python package names can't \u2014 we accept both forms on the CLI
# (``vllm-cuda`` or ``vllm_cuda``) and normalize internally.
_NAME_RE = re.compile(r"^[a-z][a-z0-9_-]*$")


def _normalize_name(raw: str) -> tuple[str, str]:
    """Return (manifest_name, python_name).

    ``manifest_name`` keeps hyphens (backend names use them by
    convention: ``hailo-ollama-npu``). ``python_name`` is the snake
    form for use in module / class identifiers.
    """
    manifest_name = raw.lower()
    python_name = manifest_name.replace("-", "_")
    return manifest_name, python_name


def _render_backend_template(raw: str) -> dict[Path, str]:
    """Build the file tree for a new third-party provider backend."""
    manifest_name, python_name = _normalize_name(raw)
    pkg = f"opencrayfish_backend_{python_name}"
    cls = (
        "".join(part.capitalize() for part in python_name.split("_"))
        + "Backend"
    )
    protocol = sorted(SUPPORTED_BACKEND_PROTOCOL_VERSIONS)[-1]
    dist_name = pkg.replace("_", "-")

    pyproject = dedent(f'''\
        [project]
        name = "{dist_name}"
        version = "0.1.0"
        description = "OpenCrayFish provider backend: {manifest_name}"
        requires-python = ">=3.13"
        dependencies = []

        [project.entry-points."opencrayfish.provider_backends"]
        {python_name} = "{pkg}:{cls}"

        [build-system]
        requires = ["setuptools>=68", "wheel"]
        build-backend = "setuptools.build_meta"

        [tool.setuptools.packages.find]
        include = ["{pkg}*"]
    ''')

    init_py = dedent(f'''\
        """OpenCrayFish provider backend: {manifest_name}.

        Auto-generated by ``opencrayfish provider new``. Replace this
        docstring + the TODO blocks below with your real backend.

        A backend implements the minimal Provider contract:

          * ``name`` (str)
          * ``async def generate(system_prompt, messages) -> str``
          * ``async def aclose() -> None``

        See ``core/provider.py::_OllamaCompatibleBackend`` for a
        worked example.
        """
        from __future__ import annotations

        from dataclasses import dataclass

        from core.provider_manifest import BackendManifest


        @dataclass
        class ChatMessage:
            """Minimal message shape the Provider passes down.

            Mirrors ``core.provider.ChatMessage`` \u2014 we don't import
            from core to keep this package importable in isolation.
            """

            role: str
            content: str


        class {cls}:
            manifest = BackendManifest(
                name="{manifest_name}",
                description=(
                    "TODO: one-line purpose of the {manifest_name} backend."
                ),
                compat_version="{protocol}",
                # Common choices: network.outbound (HTTP API client),
                # subprocess (local llama.cpp wrapper), gpu, npu.
                requires_caps=(),
                # Optional cfg.plugins.<key> namespace this backend
                # reads (model name, endpoint URL, API key, \u2026).
                config_key=None,
            )

            # Mirror manifest.name so the Provider's circuit-breaker
            # log line can read it without going through the manifest.
            name: str = "{manifest_name}"

            def __init__(self) -> None:
                # TODO: open HTTP client / spawn subprocess / load
                # weights here. The Provider constructs you once at
                # boot and reuses across all turns.
                ...

            async def generate(
                self,
                system_prompt: str,
                messages: list[ChatMessage],
            ) -> str:
                """Run inference and return the assistant reply.

                MUST raise on transport / model failure so the
                Provider's circuit-breaker can route to the fallback
                backend. Returning an empty string is treated as a
                successful but empty reply, NOT a failure.
                """
                # TODO: real implementation here.
                raise NotImplementedError(
                    "TODO: implement {manifest_name} backend"
                )

            async def aclose(self) -> None:
                """Called once at agent shutdown. Release HTTP
                clients, kill subprocesses, free GPU memory, \u2026"""
                return None
    ''')

    readme = dedent(f'''\
        # {dist_name}

        Third-party provider backend for
        [OpenCrayFish](https://github.com/easonlai/OpenCrayFish).

        ## Install

        ```bash
        pip install -e .
        ```

        Then start OpenCrayFish \u2014 your backend is auto-discovered via
        the `opencrayfish.provider_backends` entry-point group. Look
        for this line in the boot log:

        ```
        BACKEND Discovered N external backend(s) via entry-points: ..., {manifest_name}, ...
        ```

        > NB: Today the Provider singleton's primary/fallback wiring
        > is hard-coded around the Pi 5 + AI HAT+ deployment target.
        > Discovered backends are LOGGED only; a future
        > `cfg.hardware.primary = "{manifest_name}"` knob will route
        > a named external backend into the primary slot.

        ## Validate before publishing

        ```bash
        opencrayfish provider validate {pkg}:{cls}
        ```
    ''')

    test_py = dedent(f'''\
        """Minimal sanity test for the {manifest_name} backend."""
        from {pkg} import {cls}
        from core.provider_manifest import resolve_backend_manifest


        def test_manifest_resolves() -> None:
            m = resolve_backend_manifest({cls}())
            assert m.name == "{manifest_name}"
            assert m.compat_version == "{protocol}"
    ''')

    return {
        Path("pyproject.toml"): pyproject,
        Path(pkg) / "__init__.py": init_py,
        Path("README.md"): readme,
        Path("tests") / f"test_{python_name}.py": test_py,
    }


def cmd_provider_new(args: argparse.Namespace) -> int:
    raw = args.name
    if not _NAME_RE.match(raw.lower()):
        print(
            f"error: backend name {raw!r} must match {_NAME_RE.pattern} "
            "(lowercase letters/digits/underscore/hyphen, must start "
            "with a letter)",
            file=sys.stderr,
        )
        return 2

    manifest_name, python_name = _normalize_name(raw)
    dest = Path(args.dest).resolve()
    target = dest / f"opencrayfish-backend-{manifest_name.replace('_', '-')}"
    if target.exists() and not args.force:
        print(
            f"error: {target} already exists. Use --force to overwrite.",
            file=sys.stderr,
        )
        return 2

    files = _render_backend_template(raw)
    target.mkdir(parents=True, exist_ok=True)
    for rel, content in files.items():
        path = target / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print(f"created {path.relative_to(dest)}")

    print()
    print(f"Scaffolded provider backend {manifest_name!r} at {target}")
    print("Next steps:")
    print(f"  cd {target}")
    print("  pip install -e .")
    print(
        "  # restart OpenCrayFish; your backend is now logged at boot."
    )
    return 0


def cmd_provider_validate(args: argparse.Namespace) -> int:
    spec = args.target
    if ":" not in spec:
        print(
            f"error: target must be 'module:attr' (e.g. "
            f"'opencrayfish_backend_foo:FooBackend'), got {spec!r}",
            file=sys.stderr,
        )
        return 2
    mod_name, attr = spec.split(":", 1)
    try:
        mod = importlib.import_module(mod_name)
    except Exception as exc:
        print(f"error: import {mod_name!r} failed: {exc}", file=sys.stderr)
        return 3
    if not hasattr(mod, attr):
        print(
            f"error: module {mod_name!r} has no attribute {attr!r}",
            file=sys.stderr,
        )
        return 3
    obj = getattr(mod, attr)
    backend = obj() if isinstance(obj, type) else obj

    if not hasattr(backend, "generate") or not callable(
        getattr(backend, "generate", None)
    ):
        print(
            "error: backend missing async ``generate`` coroutine "
            "(must accept system_prompt, messages)",
            file=sys.stderr,
        )
        return 4

    try:
        m = resolve_backend_manifest(backend)
    except Exception as exc:
        print(f"error: manifest resolution failed: {exc}", file=sys.stderr)
        return 4
    print(f"ok: resolved manifest for {m.name!r}")
    print(f"  description    = {m.description!r}")
    print(f"  compat_version = {m.compat_version}")
    print(f"  requires_caps  = {list(m.requires_caps)}")
    print(f"  config_key     = {m.config_key!r}")
    return 0
