"""core._cli_tool — `opencrayfish tool new` + `tool validate` helpers.

Split out from ``core/cli.py`` so the heavy triple-quoted template
strings live in a dedicated file (keeps the public CLI module shorter
and lets us iterate on the template without re-touching argparse).

Mirrors ``core/cli.py``'s skill-side helpers exactly — same arg shape,
same exit codes, same print contract. The only differences are:

* Template emits ``async def call(...)`` (Tool Protocol verb), not
  ``execute(...)`` (Skill Protocol verb).
* pyproject entry-point group is ``opencrayfish.tools``.
* ``validate`` exercises ``ToolRegistry`` (not ``SkillRegistry``).
"""
from __future__ import annotations

import argparse
import importlib
import re
import sys
from pathlib import Path
from textwrap import dedent

from tools import (
    SUPPORTED_TOOL_PROTOCOL_VERSIONS,
    ToolRegistry,
    resolve_tool_manifest,
)

# Same constraint as skills: directory name must also be a legal
# Python package identifier.
_NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")


def _render_tool_template(name: str) -> dict[Path, str]:
    """Build the file tree for a new third-party Tool package."""
    pkg = f"opencrayfish_tool_{name}"
    cls = "".join(part.capitalize() for part in name.split("_")) + "Tool"
    protocol = sorted(SUPPORTED_TOOL_PROTOCOL_VERSIONS)[-1]

    pyproject = dedent(f'''\
        [project]
        name = "{pkg.replace("_", "-")}"
        version = "0.1.0"
        description = "OpenCrayFish tool: {name}"
        requires-python = ">=3.13"
        dependencies = []

        [project.entry-points."opencrayfish.tools"]
        {name} = "{pkg}:{cls}"

        [build-system]
        requires = ["setuptools>=68", "wheel"]
        build-backend = "setuptools.build_meta"

        [tool.setuptools.packages.find]
        include = ["{pkg}*"]
    ''')

    init_py = dedent(f'''\
        """OpenCrayFish tool: {name}.

        Auto-generated by ``opencrayfish tool new``. Replace this
        docstring + the TODO blocks below with your real implementation.
        """
        from __future__ import annotations

        from typing import Any

        # ToolManifest is the declarative contract the OpenCrayFish core
        # reads at boot. Required fields: name, description.
        # ``requires_caps`` documents the runtime surface area the tool
        # touches (e.g. "network.outbound", "filesystem.read", "gpio");
        # the operator can audit this without reading code.
        from tools import ToolManifest, ToolResult


        class {cls}:
            manifest = ToolManifest(
                name="{name}",
                description="TODO: one-line purpose of the {name} tool.",
                compat_version="{protocol}",
                args_schema={{
                    "query": {{
                        "type": "string",
                        "required": True,
                        "desc": "TODO: describe the query argument.",
                    }},
                }},
                # Set True if this tool mutates external state (writes
                # files, calls APIs that POST, toggles GPIO, etc.).
                side_effects=False,
                # Set True for irreversible / privileged actions; the
                # core will refuse to call without explicit op consent.
                requires_confirmation=False,
                # Capability tokens the operator can audit at boot.
                # Use well-known tokens where possible — see
                # WELL_KNOWN_TOOL_CAPABILITIES.
                requires_caps=(),
                # Optional cfg.plugins.<key> namespace this tool reads.
                # When set, the core fails loud at boot if the
                # corresponding cfg.plugins.<key> section is missing.
                config_key=None,
            )

            # Mirror the manifest fields as class attributes so legacy
            # callers using duck-typed getattr continue to work.
            name: str = "{name}"
            description: str = "TODO: one-line purpose of the {name} tool."

            async def call(self, **kwargs: Any) -> ToolResult:
                """Implement your tool here.

                Tools MUST NEVER raise — wrap failures in
                ``ToolResult(ok=False, error=...)``. See the
                ``SearXNG`` tool in OpenCrayFish's own source for
                a worked example.
                """
                query = kwargs.get("query", "")
                if not isinstance(query, str) or not query.strip():
                    return ToolResult(
                        ok=False,
                        error="missing or empty 'query' argument",
                    )
                # TODO: real implementation here.
                return ToolResult(
                    ok=True,
                    summary=f"{name} placeholder reply for {{query!r}}",
                    data={{}},
                )

            async def aclose(self) -> None:
                """Called once by the registry at agent shutdown.
                Release any held resources (HTTP clients, file
                handles, GPIO claims, ...). No-op is fine when
                there's nothing to close."""
                return None
    ''')

    readme = dedent(f'''\
        # opencrayfish-tool-{name.replace("_", "-")}

        Third-party Tool for [OpenCrayFish](https://github.com/easonlai/OpenCrayFish).

        ## Install

        ```bash
        pip install -e .
        ```

        Then start OpenCrayFish — your tool is auto-discovered via the
        `opencrayfish.tools` entry-point group. Look for this line in
        the boot log:

        ```
        TOOL Discovered N external tool(s) via entry-points: ..., {name}, ...
        ```

        ## Validate before publishing

        ```bash
        opencrayfish tool validate {pkg}:{cls}
        ```
    ''')

    test_py = dedent(f'''\
        """Minimal sanity test for the {name} tool."""
        from {pkg} import {cls}
        from tools import resolve_tool_manifest


        def test_manifest_resolves() -> None:
            m = resolve_tool_manifest({cls}())
            assert m.name == "{name}"
            assert m.compat_version == "{protocol}"
    ''')

    return {
        Path("pyproject.toml"): pyproject,
        Path(pkg) / "__init__.py": init_py,
        Path("README.md"): readme,
        Path("tests") / f"test_{name}.py": test_py,
    }


def cmd_tool_new(args: argparse.Namespace) -> int:
    name = args.name.lower()
    if not _NAME_RE.match(name):
        print(
            f"error: tool name {args.name!r} must match {_NAME_RE.pattern} "
            "(lowercase letters/digits/underscore, must start with a letter)",
            file=sys.stderr,
        )
        return 2

    dest = Path(args.dest).resolve()
    target = dest / f"opencrayfish-tool-{name.replace('_', '-')}"
    if target.exists() and not args.force:
        print(
            f"error: {target} already exists. Use --force to overwrite.",
            file=sys.stderr,
        )
        return 2

    files = _render_tool_template(name)
    target.mkdir(parents=True, exist_ok=True)
    for rel, content in files.items():
        path = target / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print(f"created {path.relative_to(dest)}")

    print()
    print(f"Scaffolded tool {name!r} at {target}")
    print("Next steps:")
    print(f"  cd {target}")
    print("  pip install -e .")
    print("  # restart OpenCrayFish; your tool is now auto-registered.")
    return 0


def cmd_tool_validate(args: argparse.Namespace) -> int:
    spec = args.target
    if ":" not in spec:
        print(
            f"error: target must be 'module:attr' (e.g. "
            f"'opencrayfish_tool_foo:FooTool'), got {spec!r}",
            file=sys.stderr,
        )
        return 2
    mod_name, attr = spec.split(":", 1)
    try:
        mod = importlib.import_module(mod_name)
    except Exception as exc:
        print(f"error: import {mod_name!r} failed: {exc}", file=sys.stderr)
        return 3
    if not hasattr(mod, attr):
        print(
            f"error: module {mod_name!r} has no attribute {attr!r}",
            file=sys.stderr,
        )
        return 3
    obj = getattr(mod, attr)
    tool = obj() if isinstance(obj, type) else obj

    try:
        m = resolve_tool_manifest(tool)
    except Exception as exc:
        print(f"error: manifest resolution failed: {exc}", file=sys.stderr)
        return 4
    print(f"ok: resolved manifest for {m.name!r}")
    print(f"  description           = {m.description!r}")
    print(f"  compat_version        = {m.compat_version}")
    print(f"  side_effects          = {m.side_effects}")
    print(f"  requires_confirmation = {m.requires_confirmation}")
    print(f"  requires_caps         = {list(m.requires_caps)}")
    print(f"  config_key            = {m.config_key!r}")

    # Dry-register so duplicate-name / protocol-mismatch problems
    # surface here rather than at user-runtime boot.
    reg = ToolRegistry()
    try:
        reg.register(tool)
    except ValueError as exc:
        print(f"error: register() rejected the tool: {exc}", file=sys.stderr)
        return 4
    problems = reg.bootstrap_validate(plugins_config=None, strict=False)
    if problems:
        print("problems:")
        for p in problems:
            print(f"  - {p}")
        return 4
    print("ok: bootstrap_validate clean (config-key check skipped — no plugins config)")
    return 0
