"""core._cli_connector \u2014 `opencrayfish connector new` + `connector validate` helpers.

Split out from ``core/cli.py`` so the heavy triple-quoted template
strings live in a dedicated file (keeps the public CLI module shorter
and lets us iterate on the template without re-touching argparse).

Mirrors ``core/_cli_tool.py`` exactly \u2014 same arg shape, same exit
codes, same print contract. The only differences are:

* Template emits ``async def start(...)`` + ``async def stop(...)``
  (Connector duck-typed surface), not ``call(...)`` / ``execute(...)``.
* pyproject entry-point group is ``opencrayfish.connectors``.
* ``validate`` exercises ``ConnectorRegistry``.
"""
from __future__ import annotations

import argparse
import importlib
import re
import sys
from pathlib import Path
from textwrap import dedent

from connectors import (
    SUPPORTED_CONNECTOR_PROTOCOL_VERSIONS,
    ConnectorRegistry,
    resolve_connector_manifest,
)

_NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")


def _render_connector_template(name: str) -> dict[Path, str]:
    """Build the file tree for a new third-party Connector package."""
    pkg = f"opencrayfish_connector_{name}"
    cls = "".join(part.capitalize() for part in name.split("_")) + "Connector"
    protocol = sorted(SUPPORTED_CONNECTOR_PROTOCOL_VERSIONS)[-1]

    pyproject = dedent(f'''\
        [project]
        name = "{pkg.replace("_", "-")}"
        version = "0.1.0"
        description = "OpenCrayFish connector: {name}"
        requires-python = ">=3.13"
        dependencies = []

        [project.entry-points."opencrayfish.connectors"]
        {name} = "{pkg}:{cls}"

        [build-system]
        requires = ["setuptools>=68", "wheel"]
        build-backend = "setuptools.build_meta"

        [tool.setuptools.packages.find]
        include = ["{pkg}*"]
    ''')

    init_py = dedent(f'''\
        """OpenCrayFish connector: {name}.

        Auto-generated by ``opencrayfish connector new``. Replace this
        docstring + the TODO blocks below with your real implementation.

        A Connector is an I/O surface \u2014 the agent's bridge to a chat
        transport (Discord, Matrix, MQTT, \u2026), a webhook endpoint, a
        voice loop, etc. The Connector contract is duck-typed:

          * ``name`` (str)  \u2014 registry key, must match manifest.name.
          * ``manifest`` (ConnectorManifest) \u2014 declarative metadata.
          * ``async def start()`` \u2014 called once at agent boot; bind
            sockets, open clients, start polling tasks here.
          * ``async def stop()``  \u2014 called once at agent shutdown;
            cleanly release every resource ``start()`` claimed.
        """
        from __future__ import annotations

        from typing import Any

        # ConnectorManifest is the declarative contract the OpenCrayFish
        # core reads at boot. Required fields: name, description.
        # ``requires_caps`` documents the runtime surface area the
        # connector touches (e.g. "network.outbound", "network.inbound",
        # "ipc.local"); the operator can audit this without reading
        # code.
        from connectors import ConnectorManifest


        class {cls}:
            manifest = ConnectorManifest(
                name="{name}",
                description="TODO: one-line purpose of the {name} connector.",
                compat_version="{protocol}",
                # Capability tokens the operator can audit at boot.
                # Common choices: network.outbound (HTTP client),
                # network.inbound (server), ipc.local (unix socket).
                requires_caps=(),
                # Optional cfg.plugins.<key> namespace this connector
                # reads. When set, the core fails loud at boot if the
                # corresponding cfg.plugins.<key> section is missing.
                config_key=None,
            )

            # Mirror the manifest fields as class attributes so legacy
            # callers using duck-typed getattr continue to work.
            name: str = "{name}"

            def __init__(self) -> None:
                # TODO: accept whatever construction args your connector
                # needs (brain, heartbeat, stm, intent_router, config,
                # \u2026). For wiring through entry-points discovery you'll
                # likely want a separate factory function \u2014 see the
                # README for the factory pattern.
                self._started = False

            async def start(self) -> None:
                """Open sockets / start polling tasks / register webhooks.

                Connectors MUST NEVER raise from start() in a way that
                blocks the rest of the agent from booting \u2014 catch
                expected failures internally and log them. The core
                will still call ``stop()`` on every connector at
                shutdown, so design start/stop as a matched pair.
                """
                # TODO: real implementation here.
                self._started = True

            async def stop(self) -> None:
                """Cleanly release everything start() claimed.

                Best-effort \u2014 the registry's aclose_all() catches
                exceptions from individual connectors so a buggy
                stop() can't block the others.
                """
                self._started = False
    ''')

    readme = dedent(f'''\
        # opencrayfish-connector-{name.replace("_", "-")}

        Third-party Connector for [OpenCrayFish](https://github.com/easonlai/OpenCrayFish).

        ## Install

        ```bash
        pip install -e .
        ```

        Then start OpenCrayFish \u2014 your connector is auto-discovered via
        the `opencrayfish.connectors` entry-point group. Look for this
        line in the boot log:

        ```
        CONNECTOR Discovered N external connector(s) via entry-points: ..., {name}, ...
        ```

        ## Validate before publishing

        ```bash
        opencrayfish connector validate {pkg}:{cls}
        ```

        ## Factory pattern (when your connector needs config)

        The default scaffold exposes the class directly so discovery
        can call ``{cls}()`` with zero args. If your connector needs
        runtime config (API keys, server URLs, \u2026), expose a factory
        instead:

        ```python
        def make_connector():
            from yourapp_config import load
            return {cls}(api_key=load().api_key)
        ```

        Then point the entry-point at the factory:

        ```toml
        [project.entry-points."opencrayfish.connectors"]
        {name} = "{pkg}:make_connector"
        ```
    ''')

    test_py = dedent(f'''\
        """Minimal sanity test for the {name} connector."""
        from {pkg} import {cls}
        from connectors import resolve_connector_manifest


        def test_manifest_resolves() -> None:
            m = resolve_connector_manifest({cls}())
            assert m.name == "{name}"
            assert m.compat_version == "{protocol}"
    ''')

    return {
        Path("pyproject.toml"): pyproject,
        Path(pkg) / "__init__.py": init_py,
        Path("README.md"): readme,
        Path("tests") / f"test_{name}.py": test_py,
    }


def cmd_connector_new(args: argparse.Namespace) -> int:
    name = args.name.lower()
    if not _NAME_RE.match(name):
        print(
            f"error: connector name {args.name!r} must match "
            f"{_NAME_RE.pattern} (lowercase letters/digits/underscore, "
            "must start with a letter)",
            file=sys.stderr,
        )
        return 2

    dest = Path(args.dest).resolve()
    target = dest / f"opencrayfish-connector-{name.replace('_', '-')}"
    if target.exists() and not args.force:
        print(
            f"error: {target} already exists. Use --force to overwrite.",
            file=sys.stderr,
        )
        return 2

    files = _render_connector_template(name)
    target.mkdir(parents=True, exist_ok=True)
    for rel, content in files.items():
        path = target / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print(f"created {path.relative_to(dest)}")

    print()
    print(f"Scaffolded connector {name!r} at {target}")
    print("Next steps:")
    print(f"  cd {target}")
    print("  pip install -e .")
    print("  # restart OpenCrayFish; your connector is now auto-registered.")
    return 0


def cmd_connector_validate(args: argparse.Namespace) -> int:
    spec = args.target
    if ":" not in spec:
        print(
            f"error: target must be 'module:attr' (e.g. "
            f"'opencrayfish_connector_foo:FooConnector'), got {spec!r}",
            file=sys.stderr,
        )
        return 2
    mod_name, attr = spec.split(":", 1)
    try:
        mod = importlib.import_module(mod_name)
    except Exception as exc:
        print(f"error: import {mod_name!r} failed: {exc}", file=sys.stderr)
        return 3
    if not hasattr(mod, attr):
        print(
            f"error: module {mod_name!r} has no attribute {attr!r}",
            file=sys.stderr,
        )
        return 3
    obj = getattr(mod, attr)
    connector = obj() if isinstance(obj, type) else obj

    try:
        m = resolve_connector_manifest(connector)
    except Exception as exc:
        print(f"error: manifest resolution failed: {exc}", file=sys.stderr)
        return 4
    print(f"ok: resolved manifest for {m.name!r}")
    print(f"  description    = {m.description!r}")
    print(f"  compat_version = {m.compat_version}")
    print(f"  requires_caps  = {list(m.requires_caps)}")
    print(f"  config_key     = {m.config_key!r}")

    reg = ConnectorRegistry()
    try:
        reg.register(connector)
    except ValueError as exc:
        print(
            f"error: register() rejected the connector: {exc}",
            file=sys.stderr,
        )
        return 4
    problems = reg.bootstrap_validate(plugins_config=None, strict=False)
    if problems:
        print("problems:")
        for p in problems:
            print(f"  - {p}")
        return 4
    print(
        "ok: bootstrap_validate clean (config-key check skipped \u2014 "
        "no plugins config)"
    )
    return 0
