"""core.cli — Operator + third-party-author CLI for OpenCrayFish.

USAGE
-----
Once installed (``pip install -e .``), the ``opencrayfish`` script is
on PATH. Today it exposes two ``skill`` subcommands:

    opencrayfish skill new <name>          # scaffold a fresh third-party skill
    opencrayfish skill validate <import>   # import + manifest-check a skill

The CLI is intentionally tiny — stdlib argparse, no typer, no
cookiecutter — so it adds zero dependencies to the runtime install.
The trade-off is that the scaffold template is inlined in this
module rather than living in a templates/ tree. When the template
set grows beyond ~3 files this should be revisited (cookiecutter is
the obvious upgrade path).

DESIGN NOTES
------------
* The CLI is its own module, NOT a subcommand of ``main.py``.
  ``main.py`` boots the agent (provider, monitor, connectors, the
  whole stack); the CLI never wants any of that. Keeping them
  separate means ``opencrayfish skill new`` runs in <100ms with no
  external services required.

* ``skill new`` writes a self-contained, ready-to-pip-install
  package directory. The generated ``pyproject.toml`` already
  declares the ``opencrayfish.skills`` entry-point, so the author
  can ``pip install -e .`` the new directory and see their skill
  show up at the next OpenCrayFish boot. No copy-paste, no manual
  ``main.py`` edits.

* ``skill validate`` is the inverse of bootstrap_validate: it
  imports a single Skill (by ``module:attr`` path), resolves its
  manifest, and prints any problems. Useful in third-party CI
  before publishing a package.
"""
from __future__ import annotations

import argparse
import importlib
import re
import sys
from pathlib import Path
from textwrap import dedent

from core.skills import (
    SUPPORTED_PROTOCOL_VERSIONS,
    SkillRegistry,
    resolve_manifest,
)
from core._cli_connector import cmd_connector_new, cmd_connector_validate
from core._cli_provider import cmd_provider_new, cmd_provider_validate
from core._cli_tool import cmd_tool_new, cmd_tool_validate


# ---------------------------------------------------------------------------
# `skill new` — scaffold a fresh third-party Skill package
# ---------------------------------------------------------------------------


# Snake-case identifier with an optional leading letter. We're more
# permissive than the registry's name validation (which only checks
# whitespace) because a *directory name* must also be a legal Python
# package — letters / digits / underscore only, can't start with a digit.
_NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")


def _render_template(name: str) -> dict[Path, str]:
    """Build the file tree for a new third-party Skill package.

    Returns a dict mapping relative path -> file content. The caller
    writes the dict to disk so file-system errors are isolated from
    the template rendering.
    """
    pkg = f"opencrayfish_skill_{name}"
    cls = "".join(part.capitalize() for part in name.split("_")) + "Skill"
    verb = name.upper()
    protocol = sorted(SUPPORTED_PROTOCOL_VERSIONS)[-1]

    pyproject = dedent(f'''\
        [project]
        name = "{pkg.replace("_", "-")}"
        version = "0.1.0"
        description = "OpenCrayFish skill: {name}"
        requires-python = ">=3.13"
        dependencies = []

        [project.entry-points."opencrayfish.skills"]
        {name} = "{pkg}:{cls}"

        [build-system]
        requires = ["setuptools>=68", "wheel"]
        build-backend = "setuptools.build_meta"

        [tool.setuptools.packages.find]
        include = ["{pkg}*"]
    ''')

    init_py = dedent(f'''\
        """OpenCrayFish skill: {name}.

        Auto-generated by ``opencrayfish skill new``. Replace this
        docstring + the TODO blocks below with your real implementation.
        """
        from __future__ import annotations

        from typing import Any

        # SkillManifest is the declarative contract the OpenCrayFish core
        # reads at boot. Required fields: name, description. Optional but
        # strongly recommended: plan_verb / plan_guidance / plan_example
        # for skills that should appear in the PLAN-stage menu.
        from core.skills import SkillContext, SkillManifest, SkillResult


        class {cls}:
            manifest = SkillManifest(
                name="{name}",
                description="TODO: one-line purpose of the {name} skill.",
                # Drop ``plan_verb`` (set to None) to keep this skill
                # invocable directly via ``skill_registry.invoke(...)``
                # but hidden from the PLAN-stage SLM menu — appropriate
                # for background-only / orchestrator-only capabilities.
                plan_verb="{verb}",
                plan_arg_hint='"<query>"',  # or "" if your verb takes no arg
                plan_guidance=(
                    "{verb} for: TODO describe when the SLM should pick "
                    "this verb vs the alternatives."
                ),
                plan_example='Q1: {verb} "<query>"',
                trigger_hints=(
                    "TODO: when does the operator want this skill?",
                ),
                args_schema={{
                    "query": {{
                        "type": "string",
                        "required": True,
                        "desc": "TODO: describe the query argument.",
                    }},
                }},
                cost_tier="cheap",        # "free" | "cheap" | "expensive"
                requires_network=False,
                # Tools this skill calls via ``ctx.tools.call(...)``.
                # The OpenCrayFish core fails loud at boot if any of
                # these are missing from the live ToolRegistry.
                requires_tools=(),
                requires_caps=(),
                compat_version="{protocol}",
            )

            async def execute(
                self, ctx: SkillContext, **kwargs: Any
            ) -> SkillResult:
                """Implement your skill here.

                Skills MUST NEVER raise — wrap failures in
                ``SkillResult(ok=False, error=...)``. See the
                ``research`` skill in OpenCrayFish's own source for
                a worked example.
                """
                query = kwargs.get("query", "")
                if not isinstance(query, str) or not query.strip():
                    return SkillResult(
                        ok=False,
                        error="missing or empty 'query' argument",
                    )
                # TODO: real implementation here.
                return SkillResult(
                    ok=True,
                    summary=f"{name} placeholder reply for {{query!r}}",
                    evidence=[],
                    tools_used=[],
                )

            async def aclose(self) -> None:
                """Called once by the registry at agent shutdown.
                Release any held resources (HTTP clients, file
                handles, …). No-op is fine when there's nothing to
                close."""
                return None
    ''')

    readme = dedent(f'''\
        # opencrayfish-skill-{name.replace("_", "-")}

        Third-party Skill for [OpenCrayFish](https://github.com/easonlai/OpenCrayFish).

        ## Install

        ```bash
        pip install -e .
        ```

        Then start OpenCrayFish — your skill is auto-discovered via the
        `opencrayfish.skills` entry-point group. Look for this line in
        the boot log:

        ```
        SKILL registered name={name} protocol={protocol} ...
        ```

        ## Validate before publishing

        ```bash
        opencrayfish skill validate {pkg}:{cls}
        ```
    ''')

    test_py = dedent(f'''\
        """Minimal sanity test for the {name} skill."""
        from {pkg} import {cls}
        from core.skills import resolve_manifest


        def test_manifest_resolves() -> None:
            m = resolve_manifest({cls}())
            assert m.name == "{name}"
            assert m.compat_version == "{protocol}"
    ''')

    return {
        Path("pyproject.toml"): pyproject,
        Path(pkg) / "__init__.py": init_py,
        Path("README.md"): readme,
        Path("tests") / f"test_{name}.py": test_py,
    }


def _cmd_new(args: argparse.Namespace) -> int:
    name = args.name.lower()
    if not _NAME_RE.match(name):
        print(
            f"error: skill name {args.name!r} must match {_NAME_RE.pattern} "
            "(lowercase letters/digits/underscore, must start with a letter)",
            file=sys.stderr,
        )
        return 2

    dest = Path(args.dest).resolve()
    target = dest / f"opencrayfish-skill-{name.replace('_', '-')}"
    if target.exists() and not args.force:
        print(
            f"error: {target} already exists. Use --force to overwrite.",
            file=sys.stderr,
        )
        return 2

    files = _render_template(name)
    target.mkdir(parents=True, exist_ok=True)
    for rel, content in files.items():
        path = target / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print(f"created {path.relative_to(dest)}")

    print()
    print(f"Scaffolded skill {name!r} at {target}")
    print("Next steps:")
    print(f"  cd {target}")
    print("  pip install -e .")
    print("  # restart OpenCrayFish; your skill is now auto-registered.")
    return 0


# ---------------------------------------------------------------------------
# `skill validate` — import + manifest-check a single third-party Skill
# ---------------------------------------------------------------------------


def _cmd_validate(args: argparse.Namespace) -> int:
    spec = args.target
    if ":" not in spec:
        print(
            f"error: target must be 'module:attr' (e.g. "
            f"'opencrayfish_skill_foo:FooSkill'), got {spec!r}",
            file=sys.stderr,
        )
        return 2
    mod_name, attr = spec.split(":", 1)
    try:
        mod = importlib.import_module(mod_name)
    except Exception as exc:
        print(f"error: import {mod_name!r} failed: {exc}", file=sys.stderr)
        return 3
    if not hasattr(mod, attr):
        print(
            f"error: module {mod_name!r} has no attribute {attr!r}",
            file=sys.stderr,
        )
        return 3
    obj = getattr(mod, attr)
    skill = obj() if isinstance(obj, type) else obj

    try:
        m = resolve_manifest(skill)
    except Exception as exc:
        print(f"error: manifest resolution failed: {exc}", file=sys.stderr)
        return 4
    print(f"ok: resolved manifest for {m.name!r}")
    print(f"  description    = {m.description!r}")
    print(f"  compat_version = {m.compat_version}")
    print(f"  plan_verb      = {m.plan_verb!r}")
    print(f"  cost_tier      = {m.cost_tier}")
    print(f"  requires_tools = {list(m.requires_tools)}")
    print(f"  requires_caps  = {list(m.requires_caps)}")

    # Also run a registry-level dry-register to surface duplicate-verb
    # or protocol-mismatch problems (bootstrap_validate skipping tool
    # checks since we don't have a tool registry here).
    reg = SkillRegistry()
    try:
        reg.register(skill)
    except ValueError as exc:
        print(f"error: register() rejected the skill: {exc}", file=sys.stderr)
        return 4
    problems = reg.bootstrap_validate(tool_registry=None, strict=False)
    if problems:
        print("problems:")
        for p in problems:
            print(f"  - {p}")
        return 4
    print("ok: bootstrap_validate clean (tool checks skipped — no ToolRegistry)")
    return 0


# ---------------------------------------------------------------------------
# argparse plumbing
# ---------------------------------------------------------------------------


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="opencrayfish",
        description="Operator + author CLI for the OpenCrayFish edge AI agent.",
    )
    sub = parser.add_subparsers(dest="domain", required=True)

    skill = sub.add_parser("skill", help="Skill scaffolding + validation")
    skill_sub = skill.add_subparsers(dest="action", required=True)

    new = skill_sub.add_parser(
        "new",
        help="Scaffold a fresh third-party Skill package in the cwd.",
    )
    new.add_argument(
        "name",
        help="Skill name (lowercase snake_case, e.g. 'translate', 'home_control').",
    )
    new.add_argument(
        "--dest",
        default=".",
        help="Parent directory to create the package in (default: cwd).",
    )
    new.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing target directory.",
    )
    new.set_defaults(func=_cmd_new)

    val = skill_sub.add_parser(
        "validate",
        help="Import a Skill by 'module:attr' and check its manifest.",
    )
    val.add_argument(
        "target",
        help="Import path, e.g. 'opencrayfish_skill_foo:FooSkill'.",
    )
    val.set_defaults(func=_cmd_validate)

    # ----- `tool` subdomain (mirror of `skill`) -----------------------------
    tool = sub.add_parser("tool", help="Tool scaffolding + validation")
    tool_sub = tool.add_subparsers(dest="action", required=True)

    tnew = tool_sub.add_parser(
        "new",
        help="Scaffold a fresh third-party Tool package in the cwd.",
    )
    tnew.add_argument(
        "name",
        help="Tool name (lowercase snake_case, e.g. 'weather', 'gpio_pwm').",
    )
    tnew.add_argument(
        "--dest",
        default=".",
        help="Parent directory to create the package in (default: cwd).",
    )
    tnew.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing target directory.",
    )
    tnew.set_defaults(func=cmd_tool_new)

    tval = tool_sub.add_parser(
        "validate",
        help="Import a Tool by 'module:attr' and check its manifest.",
    )
    tval.add_argument(
        "target",
        help="Import path, e.g. 'opencrayfish_tool_foo:FooTool'.",
    )
    tval.set_defaults(func=cmd_tool_validate)

    # ----- `connector` subdomain (mirror of `tool`) -------------------------
    connector = sub.add_parser(
        "connector", help="Connector scaffolding + validation",
    )
    connector_sub = connector.add_subparsers(dest="action", required=True)

    cnew = connector_sub.add_parser(
        "new",
        help="Scaffold a fresh third-party Connector package in the cwd.",
    )
    cnew.add_argument(
        "name",
        help="Connector name (lowercase snake_case, e.g. 'discord', 'mqtt').",
    )
    cnew.add_argument(
        "--dest", default=".",
        help="Parent directory to create the package in (default: cwd).",
    )
    cnew.add_argument(
        "--force", action="store_true",
        help="Overwrite an existing target directory.",
    )
    cnew.set_defaults(func=cmd_connector_new)

    cval = connector_sub.add_parser(
        "validate",
        help="Import a Connector by 'module:attr' and check its manifest.",
    )
    cval.add_argument(
        "target",
        help="Import path, e.g. 'opencrayfish_connector_foo:FooConnector'.",
    )
    cval.set_defaults(func=cmd_connector_validate)

    # ----- `provider` subdomain (backends) ---------------------------------
    provider = sub.add_parser(
        "provider", help="Provider backend scaffolding + validation",
    )
    provider_sub = provider.add_subparsers(dest="action", required=True)

    pnew = provider_sub.add_parser(
        "new",
        help="Scaffold a fresh third-party Provider backend package.",
    )
    pnew.add_argument(
        "name",
        help=(
            "Backend name (lowercase; hyphens allowed, e.g. "
            "'vllm-cuda', 'llamacpp-local')."
        ),
    )
    pnew.add_argument(
        "--dest", default=".",
        help="Parent directory to create the package in (default: cwd).",
    )
    pnew.add_argument(
        "--force", action="store_true",
        help="Overwrite an existing target directory.",
    )
    pnew.set_defaults(func=cmd_provider_new)

    pval = provider_sub.add_parser(
        "validate",
        help="Import a backend by 'module:attr' and check its manifest.",
    )
    pval.add_argument(
        "target",
        help=(
            "Import path, e.g. 'opencrayfish_backend_foo:FooBackend'."
        ),
    )
    pval.set_defaults(func=cmd_provider_validate)

    return parser


def main(argv: list[str] | None = None) -> int:
    parser = _build_parser()
    args = parser.parse_args(argv)
    return int(args.func(args))


if __name__ == "__main__":
    raise SystemExit(main())
